<?php

namespace Acme\DemoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ForumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumRepository extends EntityRepository
{
    public function findByForumJoinToSite($forum)
    {
        $query = $this->getEntityManager()
            ->createQuery('
            SELECT f, s FROM AcmeDemoBundle:GlSiteForum f
            JOIN f.site s
            WHERE f.forumName = :forum'
        )->setParameter('forum', $forum);

        $forum = $query->getSingleResult();

        var_dump($forum->getSite()->getName());
        return $forum;
    }
}
